/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class api_NativeClassAPI */

#ifndef _Included_api_NativeClassAPI
#define _Included_api_NativeClassAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     api_NativeClassAPI
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_api_NativeClassAPI_convertGray
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     api_NativeClassAPI
 * Method:    getSteeringAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_api_NativeClassAPI_getSteeringAngle
  (JNIEnv *, jclass);

/*
 * Class:     api_NativeClassAPI
 * Method:    getAcceleration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_api_NativeClassAPI_getAcceleration
  (JNIEnv *, jclass);

/*
 * Class:     HelloJNI
 * Method:    initFEC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_api_NativeClassAPI_initFEC
  (JNIEnv *, jobject);


/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_api_NativeClassAPI_fecEncode
  (JNIEnv *, jobject, jbyteArray, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
