/* DO NOT EDIT THIS FILE - it is machine generated */
#include <api_NativeClassAPI.h>

/*
 * Class:     api_NativeClassAPI
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_api_NativeClassAPI_convertGray
  (JNIEnv *, jclass, jlong, jlong) {
  return 0;
  }

/*
 * Class:     api_NativeClassAPI
 * Method:    getSteeringAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_api_NativeClassAPI_getSteeringAngle
  (JNIEnv *, jclass) {
  return 0.0;
  }

/*
 * Class:     api_NativeClassAPI
 * Method:    getAcceleration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_api_NativeClassAPI_getAcceleration
  (JNIEnv *, jclass) {
  return 1.0;
  }

